### ISSUE TITLE
[HOW TO CONTRIBUTE]

### ISSUE THREAD

**Issue by HassanBahati** [OSCA-Kampala-Chapter/react-ui#1]
Hi,
If you are reading this, you want to contribute to **our mission of creating the future of design systems, enabling everyone to build beautiful web apps with utility first customizable components**; thank you!

**Comment by rukundob451** [comment]
Hi @HassanBahati, thank you for sharing such a wonderful resource looking forward to contributing through for the development of beautiful web apps with utility first customizable components.

**Comment by HassanBahati** [comment]
> Hi @HassanBahati, thank you for sharing such a wonderful resource looking forward to contributing through for the development of beautiful web apps with utility first customizable components.

Hi @rukundob451, much appreciated. Looking forward to the contributions. Please checkout our Contributing Guide and [issues](https://github.com/mycro-ui/mycro-ui/issues) section.

**Comment by maddy020** [comment]
Hey @HassanBahati 
I would love to contribute over this issue

**Comment by HassanBahati** [comment]
> Hey @HassanBahati I would love to contribute over this issue

hi @maddy020 I am excited that you want to contribute. 

we are building the website lives here in this [directory](https://github.com/OSCA-Kampala-Chapter/react-ui/tree/main/website)
website tech stack
 - [next.js](https://nextjs.org/)
 - [tailwindcss](https://tailwindcss.com/)

you may also find the [figma design here](https://www.figma.com/file/BVqKE6WXA05ArKEIpsLzT8/React-UI?node-id=0%3A1&t=1YTSJnWty1Uxu77T-1)

we are building the documentation lives here in this [directory](https://github.com/OSCA-Kampala-Chapter/react-ui/tree/main/reactui-docs)

docs teach stack 
- react.js
- docusaurus v2

**Comment by rukundob451** [comment]
Thank you for this @HassanBahati.
