### ISSUE TITLE
Remove default docusaurus logo from documentation website navbar

### ISSUE THREAD

**Issue by HassanBahati** [OSCA-Kampala-Chapter/react-ui#13]
![Screenshot from 2023-01-06 12-06-43](https://user-images.githubusercontent.com/65954740/210968378-3a349f48-4128-4715-9f06-65ddae05c1a3.png)

**Comment by Pavan-Nambi** [comment]
@HassanBahati hey can u look into that ? thankyou

**Comment by HassanBahati** [comment]
> @HassanBahati hey can u look into that ? thankyou

I have. Thank you for the contribution:rocket:
