### ISSUE TITLE
Add guide to README on how to run the documentation website

### ISSUE THREAD

**Issue by HassanBahati** [OSCA-Kampala-Chapter/react-ui#15]
you may use the guidelines below, in [README.md](https://github.com/OSCA-Kampala-Chapter/react-ui/blob/main/README.md) ,create a subheading `Build Documentation Website` then add these below;

the [website directory](https://github.com/OSCA-Kampala-Chapter/react-ui/tree/main/website) is where we have the documentation that is built on top of [docusaurus v2](https://docusaurus.io/) which uses concepts of [react.js](https://reactjs.org/) so anyone that has done react can just work with it.

to run the  [website](https://github.com/OSCA-Kampala-Chapter/react-ui/tree/main/website) which also is where are going to be writing documentation.... 
1. move into the website directory `cd website`
2. install packages using `pnpm install` 
3. start the development server  `pnpm run start` which will open your browser at [http:localhost:3000](http:localhost:3000) 

[pnpm](https://pnpm.io/) is a package manger just like [npm](https://www.npmjs.com/) or [yarn](https://yarnpkg.com/)

**Comment by Rishav1707** [comment]
> you may use the guidelines below, in [README.md](https://github.com/OSCA-Kampala-Chapter/react-ui/blob/main/README.md) ,create a subheading `Build Documentation Website` then add these below;
> 
> the [website directory](https://github.com/OSCA-Kampala-Chapter/react-ui/tree/main/website) is where we have the documentation that is built on top of [docusaurus v2](https://docusaurus.io/) which uses concepts of [react.js](https://reactjs.org/) so anyone that has done react can just work with it.
> 
> to run the [website](https://github.com/OSCA-Kampala-Chapter/react-ui/tree/main/website) which also is where are going to be writing documentation....
> 
> 1. move into the website directory `cd website`
> 2. install packages using `pnpm install`
> 3. start the development server  `pnpm run start` which will open your browser at http:localhost:3000
> 
> [pnpm](https://pnpm.io/) is a package manger just like [npm](https://www.npmjs.com/) or [yarn](https://yarnpkg.com/)

Shall I work on this issue?

**Comment by HassanBahati** [comment]
> > you may use the guidelines below, in [README.md](https://github.com/OSCA-Kampala-Chapter/react-ui/blob/main/README.md) ,create a subheading `Build Documentation Website` then add these below;
> > the [website directory](https://github.com/OSCA-Kampala-Chapter/react-ui/tree/main/website) is where we have the documentation that is built on top of [docusaurus v2](https://docusaurus.io/) which uses concepts of [react.js](https://reactjs.org/) so anyone that has done react can just work with it.
> > to run the [website](https://github.com/OSCA-Kampala-Chapter/react-ui/tree/main/website) which also is where are going to be writing documentation....
> > 
> > 1. move into the website directory `cd website`
> > 2. install packages using `pnpm install`
> > 3. start the development server  `pnpm run start` which will open your browser at http:localhost:3000
> > 
> > [pnpm](https://pnpm.io/) is a package manger just like [npm](https://www.npmjs.com/) or [yarn](https://yarnpkg.com/)
> 
> Shall I work on this issue?

Hi @Rishav1707 yes you can please go ahead

**Comment by HassanBahati** [comment]
The documentation is built with docusaurus. Please find the guide in the docusaurus documentation here https://docusaurus.io/docs/installation#running-the-development-server

**Comment by HassanBahati** [comment]
Please in the readme for the reactui-documentations include the start commands and also what tools we are using to build the documentation
