### ISSUE TITLE
Add Installation guide to README

### ISSUE THREAD

**Issue by HassanBahati** [OSCA-Kampala-Chapter/react-ui#16]
you may use the guidelines below, in [README.md](https://github.com/OSCA-Kampala-Chapter/react-ui/blob/main/README.md) ,create a subheading `Installation` then add these below;

The React UI repository uses [PNPM Workspaces](https://pnpm.io/workspaces) . To install dependencies, just simply run `pnpm` in the project root directory.

PS: [pnpm](https://pnpm.io/) is a package manger just like [npm](https://www.npmjs.com/) or [yarn](https://yarnpkg.com/)

**Comment by jayanth-kumar-morem** [comment]
I would like to contribute. Can you please assign me to this?

**Comment by jayanth-kumar-morem** [comment]
- what's the minimum NodeJS version to use the package?
- I see the GitHub pages deployment failed, is there any other live URL to the documentation website?

**Comment by HassanBahati** [comment]
hi @jayanth-kumar-morem , 
please note that any node version `>=16.14` should be compatible 
https://github.com/OSCA-Kampala-Chapter/react-ui/blob/ee7d908871d7e4cbe30876e3fde56aa82b9a049a/reactui-docs/package.json#L41

for the deployment, please check again. there should be an active deployment

**Comment by HassanBahati** [comment]
Hi @jayanth-kumar-morem any progress on this?
