### ISSUE TITLE
create pull request template

### ISSUE THREAD

**Issue by HassanBahati** [OSCA-Kampala-Chapter/react-ui#21]
[Reference](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)

**Comment by c00kie123** [comment]
Hi, I am interested! Let me know any requirements you have

**Comment by HassanBahati** [comment]
hi @c00kie123 , you may base on this but also feel free to add anything else you find necessary

Check List

   - I have read the [Contributing Guidelines](CONTRIBUTING.md) and made commit messages that follow the guideline.

 -   I have run pnpm run test to check if all tests are passing, and/or pnpm run test -- -u to update snapshots if I created and/or updated React Components.
-    I have checked that the build works locally and that npm run build work fine.
 -   I've covered new added functionality with unit tests if necessary.
 - I've included issue number in the "Closes #ISSUE-NUMBER" part of the "[What are the relevant tickets?](https://github.com/airqo-platform/AirQo-frontend/blob/staging/.github/PULL_REQUEST_TEMPLATE.md#what-are-the-relevant-tickets)" section to [link the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

How should this be manually tested? Please include the steps to be done inorder to setup and test this PR.

 What are the relevant tickets?   Closes #

Screenshots (optional)

**Comment by HassanBahati** [comment]
Hi @c00kie123 any progress on this?

**Comment by HassanBahati** [comment]
> @HassanBahati Hi, should the request template visible in the repository's docs directory or in a hidden director?



hi @mosespace , it `pull request` template should be at in the [.github](https://github.com/OSCA-Kampala-Chapter/react-ui/tree/main/.github) directory

**Comment by mosespace** [comment]
@HassanBahati  I think that's what I made!

> > @HassanBahati Hi, should the request template visible in the repository's docs directory or in a hidden director?
> 
> hi @mosespace , it `pull request` template should be at in the [.github](https://github.com/OSCA-Kampala-Chapter/react-ui/tree/main/.github) directory

Hi @HassanBahati i think it's were i located it

**Comment by HassanBahati** [comment]
> Hi @HassanBahati i think it's were i located it

Yes it is located right
