### ISSUE TITLE
add `react-ui` github link to documentation navbar

### ISSUE THREAD

**Issue by HassanBahati** [OSCA-Kampala-Chapter/react-ui#23]
Reference: [react-ui github link](https://github.com/OSCA-Kampala-Chapter/react-ui) 

The `react-ui` documentation resides in the folder named as [reactui-docs](https://github.com/OSCA-Kampala-Chapter/react-ui/tree/main/reactui-docs).

Navigate to [this file](https://github.com/OSCA-Kampala-Chapter/react-ui/blob/main/reactui-docs/docusaurus.config.js#L78) and make changes to the section section below
https://github.com/OSCA-Kampala-Chapter/react-ui/blob/ee7d908871d7e4cbe30876e3fde56aa82b9a049a/reactui-docs/docusaurus.config.js#L78

**Comment by Rishav1707** [comment]
Shall I work on this issue?
