### ISSUE TITLE
deploy `website` to gh-pages

### ISSUE THREAD

**Issue by HassanBahati** [OSCA-Kampala-Chapter/react-ui#27]
the React UI website is built with [next.js](https://nextjs.org/),[ reactjs ](https://reactjs.org/) and [tailwindCSS](https://tailwindcss.com/) 

The website files are located in [this directory](https://github.com/OSCA-Kampala-Chapter/react-ui/tree/main/website)

References
https://www.viget.com/articles/host-build-and-deploy-next-js-projects-on-github-pages/

**Comment by x86Cow** [comment]
I'm interested in doing this

**Comment by HassanBahati** [comment]
hi @x86Cow yeah sure you can work on it

**Comment by HassanBahati** [comment]
Hi @x86Cow any progress on this?

**Comment by x86Cow** [comment]
Sorry, I got really busy with Midterms
