### ISSUE TITLE
add contributors graph to readme file

### ISSUE THREAD

**Issue by HassanBahati** [OSCA-Kampala-Chapter/react-ui#31]
in the [readme.md](https://github.com/OSCA-Kampala-Chapter/react-ui/blob/main/README.md) file create a sub-heading `:construction: Thanks to all Contributors`. you may use the text below to generate the contributor graph.
```sh
Thank you for spending time to contribute to **our mission of creating the future of design systems, enabling everyone to build beautiful web apps with utility first customizable components**.  Thank you so much:heart:! Keep rocking:rocket:

[![Contributors](https://contrib.rocks/image?repo=OSCA-Kampala-Chapter/react-ui)](https://github.com/OSCA-Kampala-Chapter/react-ui/graphs/contributors)
```

**Comment by SamEarth79** [comment]
Hi, I would like to contribute to this issue, can you please assign me? This is my very first issue that I'll be taking up, so I couldn't find a better one to get started with. Thanks

**Comment by HassanBahati** [comment]
hi @SamEarth79 please go ahead, work on and open a pull request when done. thank you!

**Comment by SamEarth79** [comment]
I have raised the pull request for this, thanks!
