### ISSUE TITLE
set up commit lint and husky

### ISSUE THREAD

**Issue by HassanBahati** [OSCA-Kampala-Chapter/react-ui#32]
to help with maintaining a clean git log which is so important by ensuring that we write better, cleaner and semantic commits which are easy to understand at a glance

Reference
https://commitlint.js.org/
https://betterprogramming.pub/how-to-lint-commit-messages-with-husky-and-commitlint-b51d20a5e514

**Comment by Rishav1707** [comment]
Shall I work on this issue?

**Comment by HassanBahati** [comment]
> Shall I work on this issue?

yes @Rishav1707 you can go ahead and work on it

**Comment by HassanBahati** [comment]
@Rishav1707 does #35 address this issue too? saw there was a `husky` directory created

**Comment by Rishav1707** [comment]
> @Rishav1707 does #35 address this issue too? saw there was a `husky` directory created

No, while setting up the prettier the husky directory is created automatically.
