### ISSUE TITLE
Add Typescript to website

### ISSUE THREAD

**Issue by HassanBahati** [OSCA-Kampala-Chapter/react-ui#38]
Reference
https://dev.to/sushmeet/add-typescript-to-an-existing-nextjs-project-in-5-mins-2mik

the website lives here in this [directory](https://github.com/OSCA-Kampala-Chapter/react-ui/tree/main/website)

website tech stack
- [next.js](https://nextjs.org/)
- [tailwindcss](https://tailwindcss.com/)

**Comment by ankitk26** [comment]
Hi @HassanBahati, I would like to work on this issue.

**Comment by HassanBahati** [comment]
hi @ankitk26 you can go ahead and work on it. Looking forward to a pull request
