### ISSUE TITLE
create a Contributing Guide

### ISSUE THREAD

**Issue by HassanBahati** [OSCA-Kampala-Chapter/react-ui#4]

**Comment by Rishav1707** [comment]
Shall I work on this issue?
What information do you want on contributing guide?

**Comment by HassanBahati** [comment]
@Rishav1707 the aim of this issue is to create a file `CONTRIBUTING.md` 

for the contents of that file, this guide should give avail us with the requirements of a contributing guide. https://mozillascience.github.io/working-open-workshop/contributing/

i suggest we read through the above guide, use the pointers to come up with contents for the file. 

This may be quite some work but i trust we can work together to achieve it so please you may reach out on what you may require or for any clarity
