### ISSUE TITLE
[Discussion] : Approach to building website and documentation

### ISSUE THREAD

**Issue by HassanBahati** [OSCA-Kampala-Chapter/react-ui#44]
Hi all,

I am opening this issue for us to discuss the approach we are to take on building the React UI website and documentation website. 

**Should we settle with building one platform with [docusaurus](https://docusaurus.io/)  or build the home page with next.js and redirect to the [docusaurus](https://docusaurus.io/)  site when a user needs to check documetation?**

This two concerns ideally should be under one hood. Given that if we build a website separate from the documentation, this would mean the website would only have one purpose of a landing page (as of now) then all information would be under the documentation. This what is currently happening as the [website](https://react-ui.org/) that resides under [website directory](https://github.com/OSCA-Kampala-Chapter/react-ui/tree/main/website) and [documentation site](https://osca-kampala-chapter.github.io/react-ui/) resides under [reactui-docs](https://github.com/OSCA-Kampala-Chapter/react-ui/tree/main/reactui-docs) 

The current tech stacks are;
[reactui-docs](https://github.com/OSCA-Kampala-Chapter/react-ui/tree/main/reactui-docs) 
- [docusaurus](https://docusaurus.io/) - Features (Enables building with React, MDX, Ready for Translations, Documentation Versioning, Content Search by Algolia)

[website directory](https://github.com/OSCA-Kampala-Chapter/react-ui/tree/main/website) 
- next.js - Features(SSR, SEO, React, etc)
- tailwindcss

Ideally [docusaurus](https://docusaurus.io/)  is enough to do the job, but next.js was built on board due to more familiarity with it but [docusaurus](https://docusaurus.io/)  is React.js so it gives us the leaverage of `jsx` with `mdx` on top of other awesome features out of the box.

**What do you think?**

**Comment by HassanBahati** [comment]
cc @OSCA-Kampala-Chapter/react-ui-team  @SoulSolomon21 @Rishav1707 @maddy020 @Abeinevincent @123MwanjeMike @SamEarth79 @ankitk26 @Pavan-Nambi

**Comment by maddy020** [comment]
I thinks so we should build the homepage separate and then redirects to documentation

**Comment by Abeinevincent** [comment]
@HassanBahati its alright we can have the index(home) page separate and redirect to the docs

**Comment by HassanBahati** [comment]
thank you! we shall proceed on with that:rocket:
