### ISSUE TITLE
Fix typos

### ISSUE THREAD

**Issue by HassanBahati** [OSCA-Kampala-Chapter/react-ui#45]
The [CONTRIBUTING.md](https://github.com/OSCA-Kampala-Chapter/react-ui/blob/main/CONTRIBUTING.md) file has typos around the [Wiriting A Component](https://github.com/OSCA-Kampala-Chapter/react-ui/blob/main/CONTRIBUTING.md#wiriting-your-a-component) section 
![Screenshot from 2023-01-23 13-17-12](https://user-images.githubusercontent.com/65954740/214015788-6136c09c-1e75-4a34-8d02-194ec1d0a759.png)

**Comment by Rishav1707** [comment]
Shall I work on this issue?
