### ISSUE TITLE
Enhance issue link in `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by HassanBahati** [OSCA-Kampala-Chapter/react-ui#46]
The `[Create Issue](https://github.com/OSCA-Kampala-Chapter/react-ui/issues/new)` propagates to [this page](https://github.com/OSCA-Kampala-Chapter/react-ui/issues/new) which is the `Custom Template` but we do have other alternative templates so that narrows a contributor to only opening issues with `custom template`

This link should propagate into the `[choose template page](https://github.com/OSCA-Kampala-Chapter/react-ui/issues/new/choose)` so that contributors can have multi choice of issue template based of the category of their issue

Refer to the screenshot below for the issue link in [CONTRIBUTING.md](https://github.com/OSCA-Kampala-Chapter/react-ui/blob/main/CONTRIBUTING.md)
![Screenshot from 2023-01-23 13-45-47](https://user-images.githubusercontent.com/65954740/214021918-34c241ef-afd7-43b6-a03f-27354b2d1fb5.png)

**Comment by Pavan-Nambi** [comment]
closed the pull request due to few merge conflicts i havent pulled changes from the repo so
