### ISSUE TITLE
create a Code of Conduct

### ISSUE THREAD

**Issue by HassanBahati** [OSCA-Kampala-Chapter/react-ui#5]

**Comment by maddy020** [comment]
Hey @HassanBahati 
I would love to contribute 
Please elaborate what is required in creating this ?

**Comment by HassanBahati** [comment]
> Hey @HassanBahati I would love to contribute Please elaborate what is required in creating this ?

hi @maddy020 , the aim for this issue is to add a file `CODE_OF_CONDUCT.md` to the project directories. 
the content of that file are basically about the expected behavior and standards expected of contributors to open source software.
to achieve the contents of `CODE_OF_CONDUCT.md` file , we can adapt from any open source software code of conduct online.
here are a few references 

https://www.contributor-covenant.org/version/1/4/code-of-conduct/
https://github.com/probot/template/blob/master/CODE_OF_CONDUCT.md
