### ISSUE TITLE
Remove reactui-docs directory 

### ISSUE THREAD

**Issue by HassanBahati** [OSCA-Kampala-Chapter/react-ui#54]
The React UI docs are in the [website](https://github.com/OSCA-Kampala-Chapter/react-ui/tree/main/website) directory thereby making the [reactui-docs](https://github.com/OSCA-Kampala-Chapter/react-ui/tree/main/reactui-docs) direct unnecessary.

To close this issue, delete [reactui-docs](https://github.com/OSCA-Kampala-Chapter/react-ui/tree/main/reactui-docs)  and open a pull request

**Comment by mosespace** [comment]
hello @HassanBahati am working on this

**Comment by HassanBahati** [comment]
> hello @HassanBahati am working on this

Awesome

**Comment by mosespace** [comment]
@HassanBahati this issue needs to be closed

**Comment by HassanBahati** [comment]
> @HassanBahati this issue needs to be closed

yah sure,
