### ISSUE TITLE
Help needed!

### ISSUE THREAD

**Issue by mosespace** [OSCA-Kampala-Chapter/react-ui#71]
Hello @HassanBahati am getting problem trying to follow the [README.md](https://github.com/OSCA-Kampala-Chapter/react-ui/blob/v0.0.2-beta/website/README.md) file in the website directory but am running into the errors below! How can i get helped!

![image](https://user-images.githubusercontent.com/111237257/221355957-550abec5-c45f-4a9e-96ee-21ca466a453d.png)

![image](https://user-images.githubusercontent.com/111237257/221356433-d5e2696e-9f3b-4f5e-a423-817da69a6d53.png)

**Comment by HassanBahati** [comment]
@mosespace are you trying to run the `website`?

if yes, please change your working directory into that folder. You seem to be working from the root directory.

1. `cd website` should be able to change your directory in to the `website`
2. after which `pnpm install` will install dependencies 
3. to start devevelopent server, you can run `pnpm dev`

**Comment by HassanBahati** [comment]
For more context , The website is built using https://nextra.site/

**Comment by mosespace** [comment]
> @mosespace are you trying to run the `website`?
> 
> if yes, please change your working directory into that folder. You seem to be working from the root directory.
> 
> 1. `cd website` should be able to change your directory in to the `website`
> 2. after which `pnpm install` will install dependencies
> 3. to start devevelopent server, you can run `pnpm dev`

This worked thank you so much
