### ISSUE TITLE
Enhance license section in readme

### ISSUE THREAD

**Issue by HassanBahati** [OSCA-Kampala-Chapter/react-ui#72]
![Screenshot from 2023-02-25 15-15-00](https://user-images.githubusercontent.com/65954740/221356344-e4a69ea6-6147-4195-a707-e1452bc087a3.png)

In the [README.md](https://github.com/OSCA-Kampala-Chapter/react-ui/blob/main/README.md) file as shown above , the content just shows `MIT` . We should enhance this to a text that says `React UI is licenced under MIT licence`

**Comment by mosespace** [comment]
Am working on this
