### ISSUE TITLE
deploy documentation website

### ISSUE THREAD

**Issue by HassanBahati** [OSCA-Kampala-Chapter/react-ui#8]
Using github actions

[Reference](https://docusaurus.io/docs/next/deployment#deploy)

**Comment by maddy020** [comment]
Hey @HassanBahati 
I would like to work over this issue 
Am I Supposed to deploy branch named g-h pages ?

**Comment by HassanBahati** [comment]
> Hey @HassanBahati I would like to work over this issue Am I Supposed to deploy branch named g-h pages ?

hi @maddy020 , sorry this issue was fixed by #19 , 
what was required was to recreate a github action to handle the deploy...the file that is doing is found [here](https://github.com/OSCA-Kampala-Chapter/react-ui/blob/main/.github/workflows/build-and-deploy-docs.yml)

If you are still interested in contributing, Please look through the [issues](https://github.com/OSCA-Kampala-Chapter/react-ui/issues) , you may tag me in case you require any clarity.

**Comment by maddy020** [comment]
Ok no issue
