### ISSUE TITLE
add react-ui github repository link as path for `edit on github` in documentation website

### ISSUE THREAD

**Issue by HassanBahati** [OSCA-Kampala-Chapter/react-ui#9]
The file below contains the path 

https://github.com/OSCA-Kampala-Chapter/react-ui/blob/9f0babe7cb83754d1d2e6080e0096ec48a25fa57/reactui-docs/docusaurus.config.js#L42

https://github.com/OSCA-Kampala-Chapter/react-ui/blob/9f0babe7cb83754d1d2e6080e0096ec48a25fa57/reactui-docs/docusaurus.config.js#L49

https://github.com/OSCA-Kampala-Chapter/react-ui/blob/9f0babe7cb83754d1d2e6080e0096ec48a25fa57/reactui-docs/docusaurus.config.js#L122

**Comment by maddy020** [comment]
Hey  @HassanBahati
I would like to contribute over this issue 
Please assign it to me

**Comment by HassanBahati** [comment]
hi @maddy020 sorry this issue was fixed earlier today by #24...please check the issues section other open issues. you may tag me in case any isn't clear or need any kind of help.
